name: Test

on:
  push:
    branches:    
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: prepor/setup-pulumi@master
      with:
        version: 1.3.4
    # Use the output from the `hello` step
    - run: pulumi version
